server:
  tomcat:
    max-connections: 20000     # 8192 -> 상향
    accept-count: 2000         # 100  -> 상향 (대기열)
    threads:
      max: 500                 # 200  -> 상향 (요청 처리 스레드)
      min-spare: 50
spring:
  application:
    name: ticketrace
  datasource:
    #docker 사용시 변경
    url: jdbc:mysql://localhost:3307/test
    username: root
    password: test
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
#        format_sql: true
        format_sql: false
#        highlight_sql: true
        highlight_sql: false
#        use_sql_comments: true
        use_sql_comments: false
    show-sql: false
  data:
    redis:
      host: localhost
      port: 6379
#logging:
#  level:
#    org.hibernate.SQL: DEBUG
#    org.hibernate.orm.jdbc.bind: TRACE
#    org.hibernate.orm.jdbc.extract: TRACE
springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true

  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    disable-swagger-default-url: true
    operationsSorter: method
    tagsSorter: alpha
    display-request-duration: true
    persist-authorization: true

  # 문서에 잡힐 컨트롤러 범위(선택)
  packages-to-scan:
    - com.jinsu.ticketrace
  paths-to-match:
    - /**
    -
jwt:
  secret-key: b45439f38ce614823da3a34d2e06674d59a6c1c289da2e492746d19b56bdb2b88cde70f038a1dc00594b289ee9af92fd0876a2d66c621b571a8434fc23654afc
  issuer: ticketrace
  access-minutes: 15
  refresh-days: 1
# 그라파다 설정
management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
  endpoint:
    prometheus:
      enabled: true
  metrics:
    tags:
      application: my-app
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true


